[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"

[[bin]]
name="day7"
path="days/day7.rs"

[[bin]]
name="day8"
path="days/day8.rs"

[[bin]]
name="day9"
path="days/day9.rs"

[[bin]]
name="day11"
path="days/day11.rs"
